name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
        submodules: true
    - uses: olafurpg/setup-scala@v13
      with:
        java-version: graalvm@
    - run: sbt test